import type {Metadata} from "next";
import {Inter} from "next/font/google";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
                                   children,
                                   preview,
                                   content
                               }: Readonly<{
    children: React.ReactNode;
    preview: React.ReactNode;
    content: React.ReactNode;
}>) {
    return (
        <div className={inter.className}>
            {children}
            <div className={'grid grid-cols-2'}>
                {preview}
                {content}
            </div>
        </div>
    );
}
